### ISSUE TITLE
Making inlining of attachments in html optional

### ISSUE THREAD

**Issue by DaemonicTrolley** [ram-sharma-6453/email-mime-parser#4]
This library seems to do everything I'm looking for except that it insists on putting inline attachments back inline in the html body (they are transmitted as separate MIME parts in the email but by the time I get an Email object from this library they are back inside the html body).  I need to keep them separate.
It would be very helpful if a parameter could be introduced to allow this behaviour to be switched off.

**Comment by ram-sharma-6453** [comment]
>> This library seems to do everything I'm looking for except that it insists on putting inline attachments back inline in the html body

The inline attachments are meant to be displayed inside the email main body, that's why the library behaves so (RFC : 2183).

>> (they are transmitted as separate MIME parts in the email but by the time I get an Email object from this library they are back inside the html body).

The email stream is defined like that way only , Email needs to be constructed back from raw mime parts to be displayed at the end email client.

>>  I need to keep them separate.
>> It would be very helpful if a parameter could be introduced to allow this behaviour to be switched off.

I won't be able to introduce a separate parameter to switch off the default right behavior of the library, that would lead to lot of confusion for other users.

For your special case I would suggest you to fork/compile the main branch locally for your use and comment the following method in 'Email.java' class : (line no. 238)
`replaceInlineImageAttachmentsInHtmlBody();`

You will get all the attachments the way you want via the following method as usual :
`email.getAttachments()`

**Comment by ram-sharma-6453** [comment]
Closed
